CREATE TABLE IF NOT EXISTS categories
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredients
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL,
  category_id VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS recipes
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe_ingredients
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  recipe_id VARCHAR(60),
  ingredient_id VARCHAR(60)
);
