CREATE TABLE IF NOT EXISTS categories
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  shop_order NUMBER(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredients
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL,
  category_id VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS recipes
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL,
  favorite BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS recipe_ingredients
(
  id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  recipe_id VARCHAR(60) NOT NULL,
  ingredient_id VARCHAR(60) NOT NULL
);
