POST http://localhost:8080/api/addMenuItem
Content-Type: application/json

{"name": "een"}

###

POST http://localhost:8080/api/addMenuItem
Content-Type: application/json

{"name": "twee"}

###

POST http://localhost:8080/api/addMenuItem
Content-Type: application/json

{"name": "drie"}

### Get all the messages
GET http://localhost:8080/api/menuitems
