### Post 'Hello!"
POST http://localhost:8080/
Content-Type: application/json

{
  "item": "Hello!"
}

### Post "Bonjour!"

POST http://localhost:8080/
Content-Type: application/json

{
  "item": "Bonjour!"
}

### Post "Privet!"

POST http://localhost:8080/
Content-Type: application/json

{
  "item": "Privet!"
}

### Get all the messages
GET http://localhost:8080/
